jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/radiocdn/xerosradio/assets/javascript/djonair.js
            https://cdn.jsdelivr.net/gh/radiocdn/xerosradio/assets/javascript/djonair.min.js
            https://cdn.jsdelivr.net/gh/radiocdn/xerosradio/assets/javascript/player.js
            https://cdn.jsdelivr.net/gh/radiocdn/xerosradio/assets/javascript/player.min.js
